apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwgolms-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cwgolms-app
  template:
    metadata:
      labels:
        app: cwgolms-app
    spec:
      containers:
      - name: cwgolms-app
        image: cwgolms-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080